version: "3.8"

services:
  nats:
    container_name: nats
    image: nats:2.8.4
    # see https://docs.nats.io/jetstream/getting_started/using_docker
    command:
      - "--port"
      - "4222"
      - "--http_port"
      - "8222"
      - "--jetstream"  # 如果您設置此標誌，jetstream 功能將起作用。
      - "--store_dir"
      - "/data"
      - "--debug"
    ports:
      - "4222:4222"
      - "8222:8222"
    # volumes:
    #   - ".docker-data/nats-jet-stream:/data"
    networks: ["nats"]

  prometheus-nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command:
      - "-varz"
      - "http://nats:8222"
    # volumes:
    #   - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "7777:7777"
    networks: ["nats"]
    depends_on:
      - nats
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks: ["nats"]
  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "3000:3000"
    networks: ["nats"]
  
 # open http://localhost:3000/ admin/admin






networks:
  nats:
    name: nats