version: "3.8"

services:
  nats-1:
    image: "nats:2.8.4"
    ports:
      - "14222:4222"
      - "18222:8222"
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
    networks:
      - main

  nats-2:
    image: "nats:2.8.4"
    ports:
      - "24222:4222"
      - "28222:8222"
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--routes"
      - "nats://nats-1:6222"
    networks:
      - main

  nats-3:
    image: "nats:2.8.4"
    ports:
      - "34222:4222"
      - "38222:8222"
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--routes"
      - "nats://nats-1:6222"
    networks:
      - main

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.255.0/24
      driver: default