spring:
  application:
    name: 'consumer-monitor'
  data:
    mongodb:
      host: localhost
      port: 27017
      database: devdoc
      username: user1
      password: pw123456

server:
  port: 0

nats:
  spring:
    server: nats://localhost:14222

data-center:
  id: ${random.int[1,256]}