spring:
  cloud:
    stream:
      bindings:
        sink-in-0:
          destination: ORDERS.*
          # content-type: application/json
          group: orders
          binder: nats1
      binders:
        nats1:
          type: nats
          environment:
            nats:
              spring:
                cloud:
                  stream:
                    binder:
                      server: nats://localhost:4222

server:
  port: 0