name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'liberica'
        java-version: '17'
    - name: Grant execute permission for gradlew
      working-directory: ./lab-release/account
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        USERNAME: $GITHUB_ACTOR
        TOKEN: ${{ github.token }}
      run: ./gradlew build publish
    - name: Login Docker
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build Docker Image
      run: ./gradlew bootBuildImage --imageName=ghcr.io/$GITHUB_REPOSITORY/account-test:$GITHUB_RUN_NUMBER --builder=gcr.io/buildpacks/builder
    - name: Push Docker
      run: docker push ghcr.io/$GITHUB_REPOSITORY/account-test:$GITHUB_RUN_NUMBER